export interface SeedProduct {
  name: string
  slug: string
  description: string
  benefits: string
  usage_guide: string
  material: string
  price_cny: number
  price_ghs: number
  compare_price_ghs: number | null
  category_id: string
  in_stock: boolean
  is_featured: boolean
  availability_status?: string
  delivery_profile?: 'local' | 'standard'
  lead_time?: string
  rating: number
  review_count: number
}

export const categories = [
  {
    id: 'vibrators',
    name: 'Vibrators & Stimulators',
    slug: 'vibrators',
    description: 'Premium vibrators and stimulators for every experience level.',
    image: '/images/category-vibrators.jpg',
  },
  {
    id: 'male-pleasure',
    name: 'Male Pleasure',
    slug: 'male-pleasure',
    description: 'Designed for male pleasure and performance enhancement.',
    image: '/images/category-male.jpg',
  },
  {
    id: 'couples',
    name: 'Couples Products',
    slug: 'couples',
    description: 'Products to enhance intimacy for couples.',
    image: '/images/category-couples.jpg',
  },
  {
    id: 'lubricants',
    name: 'Lubricants & Enhancers',
    slug: 'lubricants',
    description: 'Premium lubricants and arousal enhancers.',
    image: '/images/category-lubricants.jpg',
  },
  {
    id: 'anal',
    name: 'Anal Products',
    slug: 'anal',
    description: 'Anal play products for beginners and advanced users.',
    image: '/images/category-anal.jpg',
  },
  {
    id: 'wellness',
    name: 'Wellness & Accessories',
    slug: 'wellness',
    description: 'Essential accessories and wellness products.',
    image: '/images/category-wellness.jpg',
  },
  {
    id: 'dildos',
    name: 'Dildos',
    slug: 'dildos',
    description: 'A wide range of dildos in various materials and styles.',
    image: '/images/category-dildos.jpg',
  },
  {
    id: 'herbal',
    name: 'Herbal Products',
    slug: 'herbal',
    description: 'Natural herbal supplements for vitality and wellness.',
    image: '/images/category-herbal.jpg',
  },
  {
    id: 'adult-games',
    name: 'Adult Games',
    slug: 'adult-games',
    description: 'Fun and provocative games for couples and parties.',
    image: '/images/category-adult-games.jpg',
  },
]

export const products: SeedProduct[] = [
  {
    name: 'Whisper Bullet Vibrator',
    slug: 'whisper-bullet-vibrator',
    description: 'Compact and powerful, the Whisper Bullet is the perfect entry-level vibrator. Its小巧 size makes it ideal for discreet storage and travel, while delivering surprisingly strong vibrations.',
    benefits: 'Discreet size perfect for beginners\nPowerful vibrations in a compact body\nEasy to use with intuitive single-button control\nBattery-powered for cordless play\nUltra-quiet motor for private enjoyment',
    usage_guide: 'Apply a small amount of water-based lubricant to the bullet head for enhanced sensation. Press the button to cycle through vibration modes. Clean thoroughly after each use with toy cleaner.',
    material: 'Body-safe silicone over ABS plastic',
    price_ghs: 95,
    price_cny: 27,
    compare_price_ghs: 130,
    category_id: 'vibrators',
    in_stock: true,
    is_featured: true,
    delivery_profile: 'standard',
    lead_time: '7-14 Days',
    rating: 4.6,
    review_count: 24,
  },
  {
    name: 'Pulse Wand Massager',
    slug: 'pulse-wand-massager',
    description: 'Versatile wand massager perfect for full-body relaxation and targeted pleasure. Features multiple speed settings and a flexible neck for precise positioning.',
    benefits: 'Full-body massager — also marketed as wellness device\nMultiple speed settings for customized experience\nFlexible neck for perfect positioning\nDeep, rumbling vibrations\nErgonomic handle for comfortable grip',
    usage_guide: 'Start on the lowest setting and gradually increase. Use externally for best results. The flexible head contours to your body naturally. Clean with warm water and toy cleaner after use.',
    material: 'Medical-grade silicone head, ABS plastic body',
    price_ghs: 249,
    price_cny: 70,
    compare_price_ghs: 320,
    category_id: 'vibrators',
    in_stock: true,
    is_featured: true,
    delivery_profile: 'standard',
    lead_time: '7-14 Days',
    rating: 4.8,
    review_count: 37,
  },
  {
    name: 'Aria Air-Pulse Stimulator',
    slug: 'aria-air-pulse-stimulator',
    description: 'Premium air-pulse technology that uses gentle air waves for clitoral stimulation without direct contact. Award-winning design for intense, satisfying results.',
    benefits: 'Air-pulse technology — no direct contact needed\nPremium sensation highly rated globally\nMultiple intensity levels\nRechargeable with USB-C\nWaterproof for shower use',
    usage_guide: 'Place the nozzle over the clitoris. Press power to start and cycle through intensity levels. Use a drop of lubricant around the opening for best seal. Rinse and dry after use.',
    material: 'Body-safe silicone, ABS plastic, electronic components',
    price_ghs: 350,
    price_cny: 98,
    compare_price_ghs: 450,
    category_id: 'vibrators',
    in_stock: true,
    is_featured: false,
    delivery_profile: 'standard',
    lead_time: '7-14 Days',
    rating: 4.9,
    review_count: 18,
  },
  {
    name: 'Sensual Stroker',
    slug: 'sensual-stroker',
    description: 'Premium male masturbator with textured inner canal designed for realistic sensation. Discreet, portable, and easy to clean.',
    benefits: 'Realistic textured inner canal\nDiscreet and portable design\nEasy to clean and maintain\nDurable and long-lasting material\nGreat value for regular use',
    usage_guide: 'Apply generous amount of lubricant inside the sleeve. Warm the sleeve in warm water for 2 minutes for a more realistic feel. Clean thoroughly after each use with toy cleaner and pat dry.',
    material: 'TPE (thermoplastic elastomer), ABS plastic casing',
    price_ghs: 110,
    price_cny: 31,
    compare_price_ghs: 150,
    category_id: 'male-pleasure',
    in_stock: true,
    is_featured: true,
    delivery_profile: 'standard',
    lead_time: '7-14 Days',
    rating: 4.4,
    review_count: 21,
  },
  {
    name: 'Duo Vibrating Cock Ring',
    slug: 'duo-vibrating-cock-ring',
    description: 'Dual-purpose vibrating cock ring that stimulates both partners during intercourse. The vibrating bullet targets the clitoris while the ring enhances erection firmness.',
    benefits: 'Stimulates both partners simultaneously\nEnhances erection quality and duration\nRemovable vibrator bullet\nComfortable stretchy silicone\nPerfect for couples play',
    usage_guide: 'Slide the ring over the penis before erection. Position the vibrator bulb against the clitoris during intercourse. Use plenty of water-based lubricant. Remove vibrator for cleaning.',
    material: 'Body-safe silicone, electronic vibrator',
    price_ghs: 120,
    price_cny: 34,
    compare_price_ghs: 160,
    category_id: 'male-pleasure',
    in_stock: true,
    is_featured: true,
    delivery_profile: 'standard',
    lead_time: '7-14 Days',
    rating: 4.5,
    review_count: 29,
  },
  {
    name: 'Premium Delay Spray',
    slug: 'premium-delay-spray',
    description: 'Advanced desensitizing spray to help manage premature ejaculation. Fast-acting formula with natural ingredients. Discreet pump bottle.',
    benefits: 'Helps manage premature ejaculation\nFast-acting — works within minutes\nNatural active ingredients\nDiscreet pocket-sized bottle\nEach bottle lasts 40-60 uses',
    usage_guide: 'Spray 2-3 pumps onto the most sensitive areas 5-10 minutes before intimacy. Allow to absorb. Wash off after 10 minutes if desensitization is too strong. Start with fewer pumps to gauge sensitivity.',
    material: 'Water-based with lidocaine (5%), aloe vera, chamomile extract',
    price_ghs: 75,
    price_cny: 21,
    compare_price_ghs: 100,
    category_id: 'male-pleasure',
    in_stock: true,
    is_featured: true,
    delivery_profile: 'local',
    lead_time: '1-3 Days',
    rating: 4.3,
    review_count: 42,
  },
  {
    name: 'Water-Based Lubricant 200ml',
    slug: 'water-based-lubricant-200ml',
    description: 'Premium water-based lubricant for comfortable, natural-feeling intimacy. Compatible with all materials including silicone toys and condoms.',
    benefits: 'Compatible with all toy materials and condoms\nNatural-feeling glide, not sticky\nNon-staining and easy to wash off\nUnscented and flavor-free — no irritation\nLong-lasting with a single application',
    usage_guide: 'Apply a small pump to the area of use. Reapply as needed. Add a drop of water to reactivate if it dries during play. Clean with warm water and mild soap.',
    material: 'Water-based glycerin-free formula, pH balanced',
    price_ghs: 65,
    price_cny: 18,
    compare_price_ghs: 85,
    category_id: 'lubricants',
    in_stock: true,
    is_featured: true,
    delivery_profile: 'local',
    lead_time: '1-3 Days',
    rating: 4.7,
    review_count: 56,
  },
  {
    name: 'Toy Cleaner Spray 100ml',
    slug: 'toy-cleaner-spray-100ml',
    description: 'Essential toy cleaning spray for hygienic pleasure. Kills 99.9% of bacteria while being gentle on all body-safe materials.',
    benefits: 'Kills 99.9% of bacteria on contact\nGentle on all body-safe materials\nNo rinse formula — spray and wipe\nUnscented and non-irritating\nEssential for toy hygiene and longevity',
    usage_guide: 'Spray 2-3 pumps onto toy surface after use. Wipe clean with a soft cloth or rinse with water. Allow to air dry before storing.',
    material: 'Water, benzalkonium chloride (0.13%), non-toxic surfactants',
    price_ghs: 55,
    price_cny: 15,
    compare_price_ghs: 70,
    category_id: 'wellness',
    in_stock: true,
    is_featured: true,
    delivery_profile: 'local',
    lead_time: '1-3 Days',
    rating: 4.5,
    review_count: 33,
  },
  {
    name: 'Essence Arousal Gel',
    slug: 'essence-arousal-gel',
    description: 'Warming arousal gel designed to enhance sensitivity and pleasure for women. Tingling sensation increases with intimacy and body heat.',
    benefits: 'Enhances natural arousal and sensitivity\nWarming sensation that responds to body heat\nWater-based and easy to wash off\nSafe to use with condoms\nDiscreet packaging and fast delivery',
    usage_guide: 'Apply a small amount to the clitoral area. Massage gently. The warming sensation activates with body heat and movement. Use additional lubricant if needed.',
    material: 'Water-based with natural warming agents, aloe vera, vitamin E',
    price_ghs: 80,
    price_cny: 22,
    compare_price_ghs: 110,
    category_id: 'lubricants',
    in_stock: true,
    is_featured: false,
    delivery_profile: 'local',
    lead_time: '1-3 Days',
    rating: 4.4,
    review_count: 19,
  },
  {
    name: 'Starter Butt Plug Kit',
    slug: 'starter-butt-plug-kit',
    description: 'Three-piece silicone butt plug set for gradual exploration. Small, medium, and large sizes allow comfortable progression.',
    benefits: 'Three sizes for gradual progression\nBody-safe silicone — ultra smooth\nTapered tip for easy insertion\nWide flared base for safety\nPerfect for beginners',
    usage_guide: 'Start with the smallest size. Apply generous lubricant. Insert slowly and breathe deeply. Only move to larger size when completely comfortable. Always use more lubricant than you think you need.',
    material: 'Body-safe silicone, ABS plastic base',
    price_ghs: 140,
    price_cny: 39,
    compare_price_ghs: 180,
    category_id: 'anal',
    in_stock: true,
    is_featured: false,
    delivery_profile: 'standard',
    lead_time: '7-14 Days',
    rating: 4.6,
    review_count: 15,
  },
  {
    name: 'Couples Starter Bundle',
    slug: 'couples-starter-bundle',
    description: 'The perfect starter bundle for couples exploring together. Includes vibrating cock ring, water-based lubricant, and erotic conversation cards.',
    benefits: 'Complete starter bundle for couples\nIncludes three essential products\nSaves 20% compared to individual purchase\nPerfect gift for partners\nEncourages open communication',
    usage_guide: 'Start with the conversation cards to set the mood. Use the lubricant for comfortable intimacy. Add the vibrating ring when both partners are ready.',
    material: 'Mixed materials — see individual products',
    price_ghs: 220,
    price_cny: 62,
    compare_price_ghs: 275,
    category_id: 'couples',
    in_stock: true,
    is_featured: true,
    delivery_profile: 'standard',
    lead_time: '7-14 Days',
    rating: 4.7,
    review_count: 11,
  },
  {
    name: 'Herbal Vitality Supplement',
    slug: 'herbal-vitality-supplement',
    description: 'Natural herbal supplement to support energy and vitality. Formulated with traditional West African herbs known for their energizing properties.',
    benefits: 'Supports natural energy and vitality\nTraditional West African herb formula\nEasy-to-take capsule form\nNo artificial ingredients\nSupports overall wellness',
    usage_guide: 'Take 2 capsules daily with a meal. Do not exceed recommended dosage. Consult your healthcare provider if you have any medical conditions or take prescription medication.',
    material: 'Horny goat weed extract, ginseng, maca root, tribulus terrestris — vegetarian capsules',
    price_ghs: 150,
    price_cny: 42,
    compare_price_ghs: 200,
    category_id: 'wellness',
    in_stock: true,
    is_featured: false,
    delivery_profile: 'local',
    lead_time: '1-3 Days',
    rating: 4.2,
    review_count: 27,
  },
]

export const faqs = [
  {
    id: '1',
    question: 'How discreet is the packaging?',
    answer: '100% discreet. Your order arrives in a plain brown or white box with no brand markings, logos, or product names visible. The sender name on the waybill shows "VH Logistics" — nothing that reveals the contents. We take your privacy extremely seriously.',
    category: 'delivery',
  },
  {
    id: '2',
    question: 'What payment methods do you accept?',
    answer: 'We accept MTN Mobile Money, Vodafone Cash, AirtelTigo Money, and all major Visa/Mastercard debit and credit cards. Mobile money is the fastest and most popular option for Ghanaian customers.',
    category: 'payment',
  },
  {
    id: '3',
    question: 'How long does delivery take?',
    answer: 'Within Greater Accra, we offer same-day delivery (2-4 hour window) for orders placed before 4pm. Orders after 4pm are delivered the next morning. National delivery takes 2-5 days depending on your location.',
    category: 'delivery',
  },
  {
    id: '4',
    question: 'Is there a minimum age requirement?',
    answer: 'Yes. You must be 18 years or older to purchase from Intima. We display an age verification popup on site entry and may verify age for certain orders.',
    category: 'legal',
  },
  {
    id: '5',
    question: 'What is your return policy?',
    answer: 'Due to hygiene reasons, we cannot accept returns on opened products. If your item arrives damaged or defective, contact us within 48 hours and we will replace it free of charge. All products are quality-checked before dispatch.',
    category: 'orders',
  },
  {
    id: '6',
    question: 'Will my billing statement show Intima?',
    answer: 'No. Your mobile money or bank statement will show a neutral billing descriptor. We work with our payment processor to ensure complete privacy in your transaction records.',
    category: 'privacy',
  },
  {
    id: '7',
    question: 'Do you offer free delivery?',
    answer: 'Yes! Orders over GHS 200 within Greater Accra qualify for free delivery. National delivery fees vary by location and order value.',
    category: 'delivery',
  },
  {
    id: '8',
    question: 'Are your products safe?',
    answer: 'Absolutely. All products are made from body-safe materials: medical-grade silicone, ABS plastic, borosilicate glass, or stainless steel. We source only from certified manufacturers and test samples before bulk orders. We never sell products containing phthalates or other harmful chemicals.',
    category: 'products',
  },
  {
    id: '9',
    question: 'How do I use product X?',
    answer: 'Each product page includes a detailed usage guide. For additional guidance, check our blog for tips and tutorials, or contact us on WhatsApp — we respond within 30 minutes.',
    category: 'products',
  },
  {
    id: '10',
    question: 'Can I cancel or change my order?',
    answer: 'You can cancel or modify your order within 1 hour of placement, provided it has not been dispatched. Contact us immediately on WhatsApp with your order number and we will assist you.',
    category: 'orders',
  },
]

export const blogPosts = [
  {
    title: 'A Beginner\'s Guide to Choosing Your First Vibrator',
    slug: 'beginners-guide-choosing-first-vibrator',
    excerpt: 'Not sure where to start? Our comprehensive guide walks you through everything you need to know about choosing your first vibrator — from types and materials to features and budget.',
    content: 'Choosing your first vibrator can feel overwhelming with so many options available. This guide breaks down everything you need to know...',
    image: '/images/blog-beginners-guide.jpg',
    author: 'Intima Wellness Team',
    published_at: '2025-04-15',
  },
  {
    title: '5 Ways to Improve Intimacy in Your Relationship',
    slug: '5-ways-improve-intimacy-relationship',
    excerpt: 'Building deeper intimacy doesn\'t have to be complicated. Here are five practical ways to strengthen your connection with your partner starting today.',
    content: 'Intimacy is about more than physical connection. It\'s about feeling seen, heard, and valued by your partner...',
    image: '/images/blog-intimacy.jpg',
    author: 'Intima Wellness Team',
    published_at: '2025-04-08',
  },
  {
    title: 'Understanding Lubricants: Water-Based vs Silicone',
    slug: 'understanding-lubricants-water-based-vs-silicone',
    excerpt: 'Not all lubricants are created equal. Learn the differences between water-based and silicone lubricants to find the best option for your needs.',
    content: 'Choosing the right lubricant can make a significant difference in your comfort and enjoyment...',
    image: '/images/blog-lubricants.jpg',
    author: 'Intima Wellness Team',
    published_at: '2025-03-25',
  },
]

export const testimonials = [
  {
    id: '1',
    name: 'Sarah M.',
    location: 'Accra',
    rating: 5,
    text: 'I was so nervous ordering at first, but the package arrived in a plain box with no markings at all. No one knew what was inside. This is exactly what Ghana needed.',
    product: 'Whisper Bullet Vibrator',
  },
  {
    id: '2',
    name: 'Kofi A.',
    location: 'Tema',
    rating: 5,
    text: 'Ordered the delay spray and it arrived the same day. The WhatsApp updates were great — I knew exactly when it was coming. Will definitely order again.',
    product: 'Premium Delay Spray',
  },
  {
    id: '3',
    name: 'Ama D.',
    location: 'Accra',
    rating: 5,
    text: 'The discreet packaging is no joke. It literally looks like a regular delivery. Plus being able to pay with MoMo makes everything so easy. 10/10.',
    product: 'Water-Based Lubricant',
  },
  {
    id: '4',
    name: 'Kwame B.',
    location: 'Kumasi',
    rating: 4,
    text: 'Fast delivery to Kumasi in just 3 days. The quality of the products is impressive — clearly not the cheap stuff you see on social media. Well done.',
    product: 'Duo Vibrating Cock Ring',
  },
]
